// <auto-generated />
using System;
using Exam1And2_Web2_IUSR.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Exam1And2_Web2_IUSR.Models
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20240518155230_Forth Migration")]
    partial class ForthMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Exam1And2_Web2_IUSR.Models.customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Father")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Fname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Lname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("PostalCode")
                        .HasColumnType("int");

                    b.Property<string>("phoneNumber")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("customers_pk");

                    b.ToTable("customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Customer 1",
                            Father = "Customer 1",
                            Fname = "Customer 1",
                            Lname = "Customer 1",
                            PostalCode = 1234,
                            phoneNumber = "123-123"
                        },
                        new
                        {
                            Id = 2,
                            Email = "Customer 2",
                            Father = "Customer 2",
                            Fname = "Customer 2",
                            Lname = "Customer 2",
                            PostalCode = 2345,
                            phoneNumber = "234-234"
                        },
                        new
                        {
                            Id = 3,
                            Email = "Customer 3",
                            Father = "Customer 3",
                            Fname = "Customer 3",
                            Lname = "Customer 3",
                            PostalCode = 3456,
                            phoneNumber = "345-345"
                        });
                });

            modelBuilder.Entity("Exam1And2_Web2_IUSR.Models.order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("customerId")
                        .HasColumnType("int");

                    b.Property<int>("productId")
                        .HasColumnType("int");

                    b.Property<double>("sellprice")
                        .HasColumnType("float");

                    b.HasKey("Id")
                        .HasName("orders_pk");

                    b.HasIndex("customerId");

                    b.HasIndex("productId");

                    b.ToTable("orders");
                });

            modelBuilder.Entity("Exam1And2_Web2_IUSR.Models.product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<double?>("Price")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<string>("ninStock")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("products_pk");

                    b.ToTable("products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Product 1",
                            Price = 100.0,
                            ninStock = "nin stock"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Product 2",
                            Price = 200.0,
                            ninStock = "nin stock"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Product 3",
                            Price = 300.0,
                            ninStock = "nin stock"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Product 4",
                            Price = 400.0,
                            ninStock = "nin stock"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Product 5",
                            Price = 500.0,
                            ninStock = "nin stock"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Product 6",
                            Price = 600.0,
                            ninStock = "nin stock"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Product 7",
                            Price = 700.0,
                            ninStock = "nin stock"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Product 8",
                            Price = 800.0,
                            ninStock = "nin stock"
                        });
                });

            modelBuilder.Entity("Exam1And2_Web2_IUSR.Models.order", b =>
                {
                    b.HasOne("Exam1And2_Web2_IUSR.Models.customer", "customer")
                        .WithMany("orders")
                        .HasForeignKey("customerId")
                        .IsRequired()
                        .HasConstraintName("orders___fk");

                    b.HasOne("Exam1And2_Web2_IUSR.Models.product", "product")
                        .WithMany("orders")
                        .HasForeignKey("productId")
                        .IsRequired()
                        .HasConstraintName("orders_products_Id_fk");

                    b.Navigation("customer");

                    b.Navigation("product");
                });

            modelBuilder.Entity("Exam1And2_Web2_IUSR.Models.customer", b =>
                {
                    b.Navigation("orders");
                });

            modelBuilder.Entity("Exam1And2_Web2_IUSR.Models.product", b =>
                {
                    b.Navigation("orders");
                });
#pragma warning restore 612, 618
        }
    }
}
