// <auto-generated />
using System;
using Exam1And2_Web2_IUSR.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Exam1And2_Web2_IUSR.Models
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20240518154039_First Migration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Exam1And2_Web2_IUSR.Models.customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Father")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Fname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Lname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("PostalCode")
                        .HasColumnType("int");

                    b.Property<string>("phoneNumber")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("customers_pk");

                    b.ToTable("customers");
                });

            modelBuilder.Entity("Exam1And2_Web2_IUSR.Models.order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("customerId")
                        .HasColumnType("int");

                    b.Property<int>("productId")
                        .HasColumnType("int");

                    b.Property<double>("sellprice")
                        .HasColumnType("float");

                    b.HasKey("Id")
                        .HasName("orders_pk");

                    b.HasIndex("customerId");

                    b.HasIndex("productId");

                    b.ToTable("orders");
                });

            modelBuilder.Entity("Exam1And2_Web2_IUSR.Models.product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<double?>("Price")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<string>("ninStock")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("products_pk");

                    b.ToTable("products");
                });

            modelBuilder.Entity("Exam1And2_Web2_IUSR.Models.order", b =>
                {
                    b.HasOne("Exam1And2_Web2_IUSR.Models.customer", "customer")
                        .WithMany("orders")
                        .HasForeignKey("customerId")
                        .IsRequired()
                        .HasConstraintName("orders___fk");

                    b.HasOne("Exam1And2_Web2_IUSR.Models.product", "product")
                        .WithMany("orders")
                        .HasForeignKey("productId")
                        .IsRequired()
                        .HasConstraintName("orders_products_Id_fk");

                    b.Navigation("customer");

                    b.Navigation("product");
                });

            modelBuilder.Entity("Exam1And2_Web2_IUSR.Models.customer", b =>
                {
                    b.Navigation("orders");
                });

            modelBuilder.Entity("Exam1And2_Web2_IUSR.Models.product", b =>
                {
                    b.Navigation("orders");
                });
#pragma warning restore 612, 618
        }
    }
}
